### ISSUE TITLE
bazel run //:site failed as  mkdir .jekyll-cache failed for permission issues

### ISSUE THREAD

**Issue by storypku** [bazelbuild/bazel-blog#252]
Hi team,
    I have forked this repo to get some ideas to setup my own blog site. When I tried to run `bazel build //:site`, the following errors occur:

```bash
story@story4t:/work/blog.git/bazel.blog$ bazel build //:site
INFO: Analyzed target //:site (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /work/blog.git/bazel.blog/BUILD:85:13: Action site-build failed (Exit 1) jekyll failed: error executing command jekyll build -q -s bazel-out/aarch64-fastbuild/bin/site-srcs -d bazel-out/aarch64-fastbuild/bin/site-build

Use --sandbox_debug to see verbose messages from the sandbox
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem jekyll (>= 0.a) with executable jekyll (Gem::GemNotFoundException)
        from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
        from /work/sysroot/pkgs/gems/bin/jekyll:23:in `<main>'
Target //:site failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.571s, Critical Path: 0.20s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

story@story4t:/work/blog.git/bazel.blog$ bazel build //:site --verbose_failures
INFO: Analyzed target //:site (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /work/blog.git/bazel.blog/BUILD:85:13: Action site-build failed (Exit 1): jekyll failed: error executing command 
  (cd /work/tmp/bazel/fc6a47d3d13ba4b858e8dbadfd206d7e/sandbox/linux-sandbox/14/execroot/build_bazel_blog && \
  exec env - \
    PATH=/work/sysroot/pkgs/gems/bin:/work/sysroot/bin:/work/sysroot/pkgs/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  jekyll build -q -s bazel-out/aarch64-fastbuild/bin/site-srcs -d bazel-out/aarch64-fastbuild/bin/site-build)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox jekyll failed: error executing command 
  (cd /work/tmp/bazel/fc6a47d3d13ba4b858e8dbadfd206d7e/sandbox/linux-sandbox/14/execroot/build_bazel_blog && \
  exec env - \
    PATH=/work/sysroot/pkgs/gems/bin:/work/sysroot/bin:/work/sysroot/pkgs/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  jekyll build -q -s bazel-out/aarch64-fastbuild/bin/site-srcs -d bazel-out/aarch64-fastbuild/bin/site-build)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem jekyll (>= 0.a) with executable jekyll (Gem::GemNotFoundException)
        from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
        from /work/sysroot/pkgs/gems/bin/jekyll:23:in `<main>'
Target //:site failed to build
INFO: Elapsed time: 0.473s, Critical Path: 0.21s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

story@story4t:/work/blog.git/bazel.blog$  jekyll build -q -s bazel-out/aarch64-fastbuild/bin/site-srcs -d bazel-out/aarch64-fastbuild/bin/site-build --trace
Traceback (most recent call last):
        25: from /work/sysroot/pkgs/gems/bin/jekyll:23:in `<main>'
        24: from /work/sysroot/pkgs/gems/bin/jekyll:23:in `load'
        23: from /work/sysroot/pkgs/gems/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
        22: from /work/sysroot/pkgs/gems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        21: from /work/sysroot/pkgs/gems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        20: from /work/sysroot/pkgs/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        19: from /work/sysroot/pkgs/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        18: from /work/sysroot/pkgs/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        17: from /work/sysroot/pkgs/gems/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        16: from /work/sysroot/pkgs/gems/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        15: from /work/sysroot/pkgs/gems/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
        14: from /work/sysroot/pkgs/gems/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        13: from /work/sysroot/pkgs/gems/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:30:in `process'
        12: from /work/sysroot/pkgs/gems/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:30:in `new'
        11: from /work/sysroot/pkgs/gems/gems/jekyll-4.1.1/lib/jekyll/site.rb:35:in `initialize'
        10: from /work/sysroot/pkgs/gems/gems/jekyll-4.1.1/lib/jekyll/site.rb:118:in `reset'
         9: from /work/sysroot/pkgs/gems/gems/jekyll-4.1.1/lib/jekyll/cache.rb:45:in `clear_if_config_changed'
         8: from /work/sysroot/pkgs/gems/gems/jekyll-4.1.1/lib/jekyll/cache.rb:101:in `[]='
         7: from /work/sysroot/pkgs/gems/gems/jekyll-4.1.1/lib/jekyll/cache.rb:184:in `dump'
         6: from /usr/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
         5: from /usr/lib/ruby/2.5.0/fileutils.rb:193:in `each'
         4: from /usr/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
         3: from /usr/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
         2: from /usr/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
         1: from /usr/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
/usr/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Permission denied @ dir_s_mkdir - /work/blog.git/bazel.blog/bazel-out/aarch64-fastbuild/bin/site-srcs/.jekyll-cache (Errno::EACCES)

story@story4t:/work/blog.git/bazel.blog$  mkdir -p /work/blog.git/bazel.blog/bazel-out/aarch64-fastbuild/bin/site-srcs/.jekyll-cache
mkdir: cannot create directory ‘/work/blog.git/bazel.blog/bazel-out/aarch64-fastbuild/bin/site-srcs/.jekyll-cache’: Permission denied
```

I believe that I have installed Jekyll correctly, as the quick start instructions available at https://jekyllrb.com/ runs OK.
and I have tested another Jekyll based site locally, it also works fine.

I don't think I have misused ROOT account or performed `sudo` operations. 

 I have also tested this on Ubuntu 20.04.1(x86_64) and Ubuntu 18.04(Aarch64, Jetson Xavier), the same issue persists.

My bazel version is 3.5.0, downloaded from https://github.com/bazelbuild/bazel/releases.

Any idea/suggestion is appreciated.

**Comment by storypku** [comment]
Tested again on MacOS, I noticed that the `site-srcs` directory was mode 555 rather than 755 (`site-build`), which means this directory was not writable.

```
[story@STORYAIRlocal:bin]$ pwd
/Users/story/Develop/testbed/bazel-blog/bazel-out/darwin-fastbuild/bin
[story@STORYAIRlocal:bin]$ ll -lh
total 50M
drwxr-xr-x  3 story wheel   96 11 15 14:13 _sass
-r-xr-xr-x  1 story wheel  444 11 15 14:13 bootstrap-css.args
-r-xr-xr-x  1 story wheel 700K 11 15 14:13 bootstrap-css.tar
-r-xr-xr-x  1 story wheel  701 11 15 14:13 bootstrap-images.args
-r-xr-xr-x  1 story wheel 220K 11 15 14:13 bootstrap-images.tar
-r-xr-xr-x  1 story wheel  285 11 15 14:13 bootstrap-js.args
-r-xr-xr-x  1 story wheel 110K 11 15 14:13 bootstrap-js.tar
-r-xr-xr-x  1 story wheel  301 11 15 14:13 font-awesome-css.args
-r-xr-xr-x  1 story wheel  70K 11 15 14:13 font-awesome-css.tar
-r-xr-xr-x  1 story wheel  627 11 15 14:13 font-awesome-font.args
-r-xr-xr-x  1 story wheel 760K 11 15 14:13 font-awesome-font.tar
-r-xr-xr-x  1 story wheel  15K 11 15 14:13 jekyll-files.args
-r-xr-xr-x  1 story wheel  24M 11 15 14:13 jekyll-files.tar
-r-xr-xr-x  1 story wheel  463 11 15 14:13 jekyll-tree.args
-r-xr-xr-x  1 story wheel  25M 11 15 14:13 jekyll-tree.tar
-r-xr-xr-x  1 story wheel 1.2K 11 15 14:13 site
drwxr-xr-x  2 story wheel   64 11 15 14:28 site-build
dr-xr-xr-x 17 story wheel  544 11 15 14:13 site-srcs
drwxr-xr-x  4 story wheel  128 11 15 14:13 site.runfiles
-r-xr-xr-x  1 story wheel  463 11 15 14:13 site.runfiles_manifest
```

**Comment by storypku** [comment]
Maybe this issue is caused by Jekyll versions. Maybe  Jekyll  < 4 is OK while I used 4.1.1 throughout my experiment.

Modified `scripts/jekyll.bzl` to run `jekyll build` with an extra `--disable-disk-cache` option,  and it seems OK to `bazel build //:site`. 

However, `bazel run //:site` still failed complaining about `redcarpet`:

```
$ jekyll build --disable-disk-cache -q -s bazel-out/darwin-fastbuild/bin/site-srcs -d bazel-out/darwin-fastbuild/bin/site-build --trace
Markdown processor: "redcarpet" is not a valid Markdown processor.
                    Available processors are: kramdown
```

 See https://github.com/jekyll/jekyll/issues/7838#issuecomment-537254511
